name: Install Playwright
description: Install Playwright using cache
runs:
  using: composite
  steps:
    - name: Resolve Playwright version
      id: playwright-version
      run: echo "version=$(vp exec playwright --version | awk '{print $2}')" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Cache Playwright browsers
      id: playwright-cache
      uses: actions/cache@v6
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

    - name: Install Playwright browsers and system dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: vp exec playwright install --with-deps --only-shell

    - name: Only install OS dependencies for browsers
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash
      run: vp exec playwright install-deps
