packages:
  - .
  - docs

allowBuilds:
  "@parcel/watcher": true
  esbuild: true

catalog:
  "@types/node": ^26.5.0
  "@vitest/browser-playwright": ^4.1.11
  "@vitest/coverage-istanbul": 4.1.11
  astro: ^7.3.1
  bumpp: ^12.3.0
  playwright: ^1.63.0
  sass: ^1.103.1
  typescript: npm:typescript-native-bridge@^6.0.3-bridge.16.tsgo.7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1

catalogMode: strict

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.3.1"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.3.1"
  - "@voidzero-dev/vite-plus-darwin-x64@0.3.1"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.1"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.1"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.1"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.3.1"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.1"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.1"
  - vite-plus@0.3.1

overrides:
  vite@*: "catalog:"
  playwright@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
