name: "Test"

on:
  push:
  pull_request:

jobs:
  test:
    name: "Checks & Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: voidzero-dev/setup-vp@v1.19.0
        with:
          node-version: "24"
          cache: true
      - run: vp install

      - uses: ./.github/actions/install-playwright

      - run: vp run build
      - run: vp check
      - run: vp test --coverage

  test-dist:
    name: "Test dist"
    runs-on: "ubuntu-latest"
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: voidzero-dev/setup-vp@v1.19.0
        with:
          node-version: "24"
          cache: true
      - run: vp install

      - uses: ./.github/actions/install-playwright

      - run: vp run test:dist
